import dotenv from 'dotenv';
import { connectDatabase, isDbConnected } from './config/db.js';
import { Scan } from './models/Scan.js';
import { Telemetry } from './models/Telemetry.js';
import mongoose from 'mongoose';

dotenv.config();

const INITIAL_SCANS = [
  {
    filename: 'portrait_selfie_camera.jpg',
    fileType: 'image',
    fileSize: '117.4 KB',
    fileHash: '54a63a58d35ba48c599147573f1d87e0766ef5cc315f60b7eb4aa96e6fe4eb5e',
    result: 'REAL HUMAN (AUTHENTIC)',
    confidence: 99.4,
    riskLevel: 'LOW',
    orientation: 'PORTRAIT',
    aspectRatioLabel: '9:16',
    signals: { facialSignal: 99.1, pixelSignal: 98.7, patternSignal: 99.4, temporalSignal: 99.2 },
    metrics: { facialConsistency: 99.2, pixelConsistency: 98.9, visualArtifacts: 0.8, frameConsistency: 99.5, frequencyAnomaly: 0.6, compressionNoise: 1.2 },
    detectedAnomalies: [],
    logs: [
      '[CFA] Bayer sensor matrix verified. Physical color filter array consistent.',
      '[DQT] Standard hardware quantization table detected with realistic camera sensor noise.',
      '[ELA] Uniform compression across entire frame; zero Poisson seam variance.',
      '[DECISION] 100% authenticated real human portrait capture.',
    ],
  },
  {
    filename: 'ai_generated_avatar_deepfake.jpg',
    fileType: 'image',
    fileSize: '219.9 KB',
    fileHash: 'efaf57b85e05a81667b36a1883656114a9386d34e912ca6717eb487a3250e83b',
    result: 'DEEPFAKE (FAKE)',
    confidence: 99.1,
    riskLevel: 'HIGH',
    orientation: 'PORTRAIT',
    aspectRatioLabel: '9:16',
    signals: { facialSignal: 98.6, pixelSignal: 97.9, patternSignal: 99.1, temporalSignal: 98.4 },
    metrics: { facialConsistency: 1.4, pixelConsistency: 2.1, visualArtifacts: 98.6, frameConsistency: 3.2, frequencyAnomaly: 97.8, compressionNoise: 96.4 },
    detectedAnomalies: [
      'High-frequency GAN lattice checkerboard artifacts detected',
      'Synthetic Poisson blending seam along jawline boundary',
      'Flat neural quantization table [1,1,1,1,1,1,1,1] indicating synthetic autoencoder output',
    ],
    logs: [
      '[HASH] Synthetic fingerprint detected in threat intelligence database.',
      '[DQT] Flat quantization table [1,1,1,1,1,1,1,1] generated by neural encoder.',
      '[ELA] Error Level Analysis reveals sharp compression discontinuity at facial boundary.',
      '[DECISION] Synthetically generated deepfake identified with 99.1% certainty.',
    ],
  },
  {
    filename: 'executive_video_briefing.mp4',
    fileType: 'video',
    fileSize: '24.8 MB',
    fileHash: '8a91cf27b0341e428178d8f99e31d47a523b49e1bfa780d6f443b749321e05a1',
    result: 'DEEPFAKE (FAKE)',
    confidence: 98.7,
    riskLevel: 'HIGH',
    orientation: 'LANDSCAPE',
    aspectRatioLabel: '16:9',
    signals: { facialSignal: 97.4, pixelSignal: 96.8, patternSignal: 98.5, temporalSignal: 98.7 },
    metrics: { facialConsistency: 2.8, pixelConsistency: 3.1, visualArtifacts: 97.2, frameConsistency: 1.5, frequencyAnomaly: 96.1, compressionNoise: 95.8 },
    detectedAnomalies: [
      'Temporal frame-to-frame ocular jitter detected across frames #45-#120',
      'Audio-visual phoneme desynchronization in lip-sync autoencoder',
    ],
    logs: [
      '[TEMPORAL] Inter-frame optical flow analysis detected synthetic warping.',
      '[LIP-SYNC] Wav2Lip autoencoder phoneme desynchronization confirmed.',
      '[DECISION] High-risk synthetic video deepfake flagged.',
    ],
  },
  {
    filename: 'kyc_passport_verification.png',
    fileType: 'image',
    fileSize: '840.2 KB',
    fileHash: '2bc17d89045ea612b7a9f0e1329c48b71d9a01f42e316a8b79f04523c12d45a9',
    result: 'REAL HUMAN (AUTHENTIC)',
    confidence: 99.7,
    riskLevel: 'LOW',
    orientation: 'PORTRAIT',
    aspectRatioLabel: '3:4',
    signals: { facialSignal: 99.6, pixelSignal: 99.4, patternSignal: 99.8, temporalSignal: 99.5 },
    metrics: { facialConsistency: 99.7, pixelConsistency: 99.4, visualArtifacts: 0.3, frameConsistency: 99.8, frequencyAnomaly: 0.4, compressionNoise: 0.9 },
    detectedAnomalies: [],
    logs: [
      '[BIOMETRICS] Verified 68 facial landmark geometry conforms to natural biological symmetry.',
      '[ELA] Zero tamper gradient across security document border.',
      '[DECISION] KYC identity verified as authentic.',
    ],
  },
];

const seedDatabase = async () => {
  console.log('🌱 Starting MongoDB database seeding for DeepGuard AI...');
  await connectDatabase();

  if (!isDbConnected()) {
    console.error('❌ Cannot seed: MongoDB is not connected.');
    process.exit(1);
  }

  try {
    const existingCount = await Scan.countDocuments();
    console.log(`📊 Existing scans in MongoDB: ${existingCount}`);

    if (existingCount === 0) {
      console.log('📥 Populating initial verified scans collection...');
      await Scan.insertMany(INITIAL_SCANS);
      console.log(`✅ Inserted ${INITIAL_SCANS.length} verified scans.`);
    } else {
      console.log('ℹ️ Database already has scans. Adding test scans if missing...');
      for (const item of INITIAL_SCANS) {
        await Scan.updateOne({ filename: item.filename }, { $setOnInsert: item }, { upsert: true });
      }
      console.log('✅ Synchronized test scans.');
    }

    // Initialize telemetry
    const today = new Date().toISOString().split('T')[0];
    const total = await Scan.countDocuments();
    const fakes = await Scan.countDocuments({ result: 'DEEPFAKE (FAKE)' });
    const reals = await Scan.countDocuments({ result: 'REAL HUMAN (AUTHENTIC)' });

    await Telemetry.findOneAndUpdate(
      { date: today },
      {
        totalScans: total,
        deepfakeCount: fakes,
        authenticCount: reals,
        reviewCount: total - (fakes + reals),
        averageConfidence: 99.4,
        activeThreatsBlocked: fakes,
      },
      { upsert: true, new: true }
    );

    console.log('✅ Telemetry aggregated successfully.');
    console.log('🎉 MongoDB seeding completed successfully!');
  } catch (err: any) {
    console.error('❌ Seeding error:', err);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB.');
    process.exit(0);
  }
};

seedDatabase();
